### ISSUE TITLE
USER STORY: Register with email & password

### ISSUE THREAD

**Issue by CapriceHolford** [CapriceHolford/The-Pampered-Pet-Parlor#1]
As a **user** I can **register an account with my email and password** so that **I can easily access my past/future bookings**

### Acceptance Criteria 
- Error message if password not strong enough
- Clear register button, simplified register page
-  Required email and strong password

## Tasks
- [x] Design user registration form
- [x] Make email and password required 
- [x] Set up a way to ensure a strong password is being used - i.e. character limit, add symbols 
- [x] Add a forgotten password option
