### ISSUE TITLE
USER STORY: Book Appointment Online

### ISSUE THREAD

**Issue by CapriceHolford** [CapriceHolford/The-Pampered-Pet-Parlor#2]
As a **new customer** I can **book an appointment online** so that **I can easily schedule appointments**

### Acceptance Criteria 
- Add a booking form with an option to sign up/in if you choose
- Calendar integration to see when appointments are available 
- A way to pay for appointment online or a 10% deposit if prefer to pay in store

## Tasks
- [x] Create a booking form must include customer name, contact info, dog name, dog breed and desired grooming services. If customer signs in with an account, pre filled out  
- [ ] Integrate a calendar system where you can easily see availability 
- [ ] Create a secure, required payment process with an option to pay a deposit or pay in full
- [ ] Add T&C's for missed or cancelled appointments, i.e. deposit won't be refunded if not cancelled with at least 24 hours notice, missed appointments will be charged full cost of groom via the card on system
