### ISSUE TITLE
USER STORY: Manage Appointments 

### ISSUE THREAD

**Issue by CapriceHolford** [CapriceHolford/The-Pampered-Pet-Parlor#3]
As a **existing customer** I can **sign in** so that **I can manage my appointments, cancel or book as needed**

### Acceptance Criteria 
- Must be able to login to account to access appointment history, have a reset password option if needed
- Account show show past and upcoming appointments, I can choose between calendar and list view
- A way to reschedule/cancel if applicable
- An easy way to view policies for rescheduling/cancellation 
- An option to add notifications via text if customer chooses 

## Tasks
- [x] Create a user-friendly login page
- [ ] Design an intuitive appointment history interface. Calendar/list view.
- [ ] Design clear and concise forms for rescheduling and cancellation.
- [ ] Develop backend logic to retrieve and update appointment information.
- [ ] Integrate with a notification service (e.g., Twilio) for SMS notifications.
- [ ] Integrate with the payment gateway to process refunds.
- [ ] Upon appointment rescheduling, the system should offer the user the option to:
- Refund the deposit/payment in full.
- Transfer the deposit/payment to a future appointment.
