### ISSUE TITLE
USER STORY: Newsletter

### ISSUE THREAD

**Issue by CapriceHolford** [CapriceHolford/The-Pampered-Pet-Parlor#4]
As a customer, I want to be able to sign up for email newsletters to receive updates on promotions and special offers.

#### Newsletter Sign Up Form
- A clear and concise signup form should be available on the website.
- The form should require only the user's email address.
- The form should include a checkbox for the user to agree to the privacy policy.

#### Email Confirmation:
- Upon successful signup, the user should receive a confirmation email with a link to confirm their subscription.
- The confirmation email should include a clear call to action and a link to unsubscribe.

## Tasks
- [ ] Design a simple and attractive sign up form, could be a pop up that lets you add your email, see privacy policy 
- [ ] Implement backend logic to store email addresses 
- [ ] Offer a discount code for people who do sign up to the newsletter
